# Site settings
title: Working in the Code Mines
email: luke_imhoff@rapid7.com
description: "Things I've learned while working on metasploit-framework and Metasploit Pro at Rapid7"
baseurl: ""
url: "http://limhoff-r7.github.io"

# Build settings
encoding: utf-8
kramdown:
  input: GFM
markdown: kramdown
permalink: pretty
pygments: true
